Repository TeddKo/PickaView, pull requests merged in 2025-06, with the labels that each got.

#84 [Fix] PlayerViewController 인스턴스 생성에서 스토리보드 연결로 변경
  PickaView/Views/Like/LikeViewController.swift
  PickaView/Views/Player/PlayerViewModel.swift
Labels: fix

#96 [PR] 마이페이지, 좋아요
  PickaView/Common/Components/Components.swift
  PickaView/Common/Factories/FRCFactory.swift
  PickaView/Model.xcdatamodeld/Model.xcdatamodel/contents
  PickaView/Views/Like/LikeCollectionViewCell.swift
  PickaView/Views/Like/LikeViewController.swift
  PickaView/Views/Like/LikeViewModel.swift
  PickaView/Views/MyPage/MyPage.storyboard
  PickaView/Views/MyPage/MyPageComponents.swift
  PickaView/Views/MyPage/MyPageViewController.swift
  PickaView/Views/MyPage/MyPageViewModel.swift
  PickaView/Views/MyPage/MyPageWatchedVideoCollectionViewCell.swift
  PickaView/Views/MyPage/RandomColorCollectionViewCell.swift
  PickaView/Views/MyPageHistories/MyPageHistories.storyboard
  PickaView/Views/MyPageHistories/MyPageHistoriesCollectionViewCell.swift
  PickaView/Views/MyPageHistories/MyPageHistoriesViewController.swift
Labels: PR

#109 feat: 히스토리 FRC 작업
  PickaView/Common/Factories/FRCFactory.swift
  PickaView/Data/Persistence/CoreDataManager.swift
  PickaView/Views/Like/LikeViewController.swift
  PickaView/Views/Like/LikeViewModel.swift
  PickaView/Views/MyPage/ChartView.swift
  PickaView/Views/MyPage/MyPageViewController.swift
  PickaView/Views/MyPage/MyPageViewModel.swift
Labels: PR

#111 [PR] 앱테마
  PickaView/Data/UserDefault/ThemeManager.swift
Labels: fix, PR

#127 fix: 플레이어뷰 레이아웃 수정
  PickaView/Views/Player/FullscreenPlayerViewController.swift
  PickaView/Views/Player/PlayerViewController+Gestures.swift
  PickaView/Views/Player/PlayerViewController+UI.swift
  PickaView/Views/Player/PlayerViewController+collectionViewUI.swift
  PickaView/Views/Player/PlayerViewController.swift
Labels: fix, PR

#129 Feature/components frc mypage annotation
  PickaView/Common/Components/Components.swift
  PickaView/Common/Components/Extension.swift
  PickaView/Common/Factories/FRCFactory.swift
  PickaView/Views/MyPage/MyPageComponents.swift
  PickaView/Views/Player/FullscreenPlayerViewController.swift
Labels: documentation, PR

#128 [PR]노티피케이션 제거하는 코드 추가
  PickaView/Views/Player/FullscreenPlayerViewController.swift
Labels: fix, PR

#134 [PR] 좋아요 화면 버튼 애니메이션 추가
  PickaView/Common/Components/Components.swift
  PickaView/Views/Like/LikeCollectionViewCell.swift
  PickaView/Views/Like/LikeViewController.swift
  PickaView/Views/Like/LikeViewModel.swift
Labels: fix, PR

#135 [PR] 플레이어 전체화면 했을때 뷰가 이상하게 나오는 이슈 수정
  PickaView/Views/Home/HomeViewController.swift
  PickaView/Views/Player/FullscreenPlayerViewController.swift
  PickaView/Views/Player/PlayerViewController.swift
Labels: fix, PR

#142 [Fix] AVAudioSession이 준비되지 않은 상태에서 setCategory 호출되는 경고 수정
  PickaView/Views/VideoPlayer/PlayerViewController.swift
Labels: fix

#141 Hotfix/readme
  README.md
Labels: documentation, PR

#145 [Release1.0.1] Minor Update
  PickaView/Shared/Components/Components.swift
  PickaView/Views/VideoPlayer/PlayerViewController.swift
Labels: bug, fix, PR

#149 [Release 1.0.2]
  PickaView/Data/Config/Config.xcconfig
  PickaView/Shared/Components/Components.swift
Labels: fix, PR, release

#150 [HotFix] Config
  PickaView/Data/Config/Config.xcconfig
Labels: fix, PR
